### ISSUE TITLE
TypeError: environment can only contain strings

### ISSUE THREAD

**Issue by lhz7797251** [anselal/antminer-monitor#125]
C:\antminer-monitor-master>python manage.py run -h 127.0.0.1 -p 5000
 * Serving Flask app "antminermonitor/app.py:create_app()" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Restarting with stat
Traceback (most recent call last):
  File "manage.py", line 286, in <module>
    cli()
  File "C:\ProgramData\Anaconda2\lib\site-packages\click\core.py", line 722, in
__call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\flask\cli.py", line 557, in m
ain
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\click\core.py", line 697, in
main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda2\lib\site-packages\click\core.py", line 1066, in
 invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda2\lib\site-packages\click\core.py", line 895, in
invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda2\lib\site-packages\click\core.py", line 535, in
invoke
    return callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\click\decorators.py", line 64
, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\click\core.py", line 535, in
invoke
    return callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\flask\cli.py", line 771, in r
un_command
    threaded=with_threads, ssl_context=cert)
  File "C:\ProgramData\Anaconda2\lib\site-packages\werkzeug\serving.py", line 81
2, in run_simple
    reloader_type)
  File "C:\ProgramData\Anaconda2\lib\site-packages\werkzeug\_reloader.py", line
275, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "C:\ProgramData\Anaconda2\lib\site-packages\werkzeug\_reloader.py", line
132, in restart_with_reloader
    close_fds=False)
  File "C:\ProgramData\Anaconda2\lib\subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\ProgramData\Anaconda2\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\ProgramData\Anaconda2\lib\subprocess.py", line 644, in _execute_child

    startupinfo)
TypeError: environment can only contain strings

**Comment by anselal** [comment]
This is a very risky task to be automated.
