### ISSUE TITLE
crash after adding the 18th device

### ISSUE THREAD

**Issue by asulpizi** [anselal/antminer-monitor#137]
I tried it a few times and same result.  As soon as I save teh 18th one it crashes (see traceback / error below).

C:\Users\dac\AppData\Local\Programs\Python\Python36-32\antmon>python manage.py run -h 0.0.0.0 -p 5001
 * Serving Flask app "antminermonitor/app.py:create_app()" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 263-193-197
 * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2018-10-28 20:28:20,149] INFO in antminer: [INFO] No miners added yet. Please add miners using the above form.
127.0.0.1 - - [28/Oct/2018 20:28:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:28:20] "GET /static/styles/menu.css HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:28:20] "GET /static/styles/main.css HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:28:20] "GET /static/scripts/main.js HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:28:20] "GET /static/scripts/donate.js HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:28:20] "GET /static/scripts/vendor/coin.js HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:28:20] "GET /static/styles/vendor/coin.css HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:28:21] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [28/Oct/2018 20:28:21] "GET /static/images/icon_bitcoin.png HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:28:21] "GET /static/images/icon_litecoin.png HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:28:21] "GET /static/images/icon_dash.png HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:28:21] "GET /static/images/icon_ethereum.png HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:29:06] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:29:06,047] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:29:06] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:29:06] "GET /static/images/assets/remove.png HTTP/1.1" 200 -
[2018-10-28 20:29:16,685] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:29:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:29:23] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:29:23,989] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:29:23] "GET / HTTP/1.1" 200 -
[2018-10-28 20:29:26,679] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:29:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:29:32] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:29:32,989] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:29:32] "GET / HTTP/1.1" 200 -
[2018-10-28 20:29:38,101] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:29:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:29:44] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:29:44,438] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.104'.
[2018-10-28 20:29:44,438] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:29:44] "GET / HTTP/1.1" 200 -
[2018-10-28 20:29:51,251] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.104'.
[2018-10-28 20:29:51,251] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:29:51] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:29:56] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:29:56,541] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.104'.
[2018-10-28 20:29:56,556] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.105'.
[2018-10-28 20:29:56,556] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:29:56] "GET / HTTP/1.1" 200 -
[2018-10-28 20:31:07,825] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.104'.
[2018-10-28 20:31:07,849] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.105'.
[2018-10-28 20:31:07,850] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:31:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:31:15] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:31:15,507] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.104'.
[2018-10-28 20:31:15,531] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.105'.
[2018-10-28 20:31:15,546] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:31:15] "GET / HTTP/1.1" 200 -
[2018-10-28 20:33:16,000] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.104'.
[2018-10-28 20:33:16,004] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.105'.
[2018-10-28 20:33:16,010] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:33:16] "GET / HTTP/1.1" 200 -
[2018-10-28 20:35:16,536] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:35:16] "GET / HTTP/1.1" 200 -
[2018-10-28 20:37:17,053] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:37:17] "GET / HTTP/1.1" 200 -
[2018-10-28 20:37:25,524] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:37:25] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:37:31] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:37:31,880] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:37:31] "GET / HTTP/1.1" 200 -
[2018-10-28 20:37:33,911] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:37:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:37:44] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:37:44,869] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:37:44] "GET / HTTP/1.1" 200 -
[2018-10-28 20:37:54,721] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:37:54] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:38:03] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:38:04,456] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:38:04] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:38:10] "GET /user/password_update HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:38:10] "GET /static/styles/login.css HTTP/1.1" 200 -
[2018-10-28 20:38:18,137] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:38:18] "GET / HTTP/1.1" 200 -
[2018-10-28 20:38:19,240] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:38:19] "GET / HTTP/1.1" 200 -
[2018-10-28 20:38:30,029] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:38:30] "GET / HTTP/1.1" 200 -
[2018-10-28 20:38:34,575] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:38:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:38:42] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:38:42,628] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:38:42] "GET / HTTP/1.1" 200 -
[2018-10-28 20:41:38,558] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:41:38] "GET / HTTP/1.1" 200 -
[2018-10-28 20:42:53,825] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:42:53] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:43:01] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:43:01,752] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:43:01] "GET / HTTP/1.1" 200 -
[2018-10-28 20:43:05,230] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:43:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:43:11] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:43:11,533] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:43:11] "GET / HTTP/1.1" 200 -
[2018-10-28 20:45:12,699] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:45:12] "GET / HTTP/1.1" 200 -
[2018-10-28 20:47:13,310] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.111'.
[2018-10-28 20:47:13,320] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:47:13] "GET / HTTP/1.1" 200 -
[2018-10-28 20:49:13,976] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.111'.
[2018-10-28 20:49:13,982] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:49:13] "GET / HTTP/1.1" 200 -
[2018-10-28 20:49:41,245] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.111'.
[2018-10-28 20:49:41,270] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:49:41] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:49:47] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:49:47,636] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.111'.
[2018-10-28 20:49:47,667] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:49:47] "GET / HTTP/1.1" 200 -
[2018-10-28 20:50:03,301] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.111'.
[2018-10-28 20:50:03,352] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:50:03] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:50:08] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:50:08,797] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.111'.
[2018-10-28 20:50:08,847] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:50:08] "GET / HTTP/1.1" 200 -
[2018-10-28 20:50:11,767] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.111'.
[2018-10-28 20:50:11,846] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:50:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:50:19] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:50:19,355] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.111'.
[2018-10-28 20:50:19,454] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:50:19] "GET / HTTP/1.1" 200 -
[2018-10-28 20:50:29,757] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.111'.
[2018-10-28 20:50:29,790] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:50:29] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:50:35] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:50:36,235] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.111'.
[2018-10-28 20:50:36,365] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:50:36] "GET / HTTP/1.1" 200 -
[2018-10-28 20:50:48,107] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.111'.
[2018-10-28 20:50:48,207] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:50:48] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:50:53] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:50:54,013] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.111'.
[2018-10-28 20:50:54,146] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:50:54] "GET / HTTP/1.1" 200 -
[2018-10-28 20:51:20,422] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.111'.
[2018-10-28 20:51:20,553] INFO in antminer: [INFO] All miners are operating normal. No errors found.
127.0.0.1 - - [28/Oct/2018 20:51:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:51:27] "POST /add HTTP/1.1" 302 -
[2018-10-28 20:51:27,793] WARNING in antminer: [WARNING] High temperatures on miner '10.1.1.111'.
127.0.0.1 - - [28/Oct/2018 20:51:27] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\antmon\antminermonitor\blueprints\asicminer\views\antminer.py", line 93, in miners
    miner_stats = get_stats(miner.ip)
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\antmon\lib\pycgminer.py", line 111, in get_stats
    output = cgminer.stats()
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\antmon\lib\pycgminer.py", line 90, in out
    return self.command(attr, arg)
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\antmon\lib\pycgminer.py", line 62, in command
    return json.loads(received[:-1].replace('}{', '},{'))
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\dac\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 219 (char 218)
127.0.0.1 - - [28/Oct/2018 20:51:28] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:51:28] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:51:28] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:51:28] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:51:28] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [28/Oct/2018 20:51:28] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

**Comment by anselal** [comment]
What model is the miner you are adding ?

**Comment by anselal** [comment]
Are you sure it is a S9 ? Justs it the older S9 model or the newer ones ?

Can you try it with Python 2.7 and let me know if it works ?

**Comment by asulpizi** [comment]
It’s S9 13.5 shipped new  in March.   I tried 2.7 and same thing.  I had over 20 working for many moths on your .04 code.  
The strange thing is it works fine as long as I don’t add more than 17.  All 20 S9 are the same.

**Comment by asulpizi** [comment]
I did not intend to close this.  Please advise

**Comment by anselal** [comment]
Another reason for this issue is your network setup and/or topology causing delays in the communication between the miners and the software.
Please try to increase the socket timeout in the lib/pycgminer.py file and let me know if that worked

**Comment by anselal** [comment]
I close this issue due to inactivity. Feel free to reopen
