### ISSUE TITLE
DECRED ANTMINER SUPORT

### ISSUE THREAD

**Issue by red0bear** [anselal/antminer-monitor#140]
Well like you said ... i will open this issue to we see what you can do about it. but to help i need know what info you need to make this ?

**Comment by anselal** [comment]
Which model is the decred miner ? Can't find it at bitmain's site

**Comment by anselal** [comment]
Do you mind sharing the output of:

http://127.0.0.1:5000/<miner_ip>/pools
http://127.0.0.1:5000/<miner_ip>/stats

**Comment by red0bear** [comment]
****

**Comment by red0bear** [comment]
builtins.TypeError

TypeError: Object of type 'timeout' is not JSON serializable
Traceback (most recent call last)

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__

    return self.wsgi_app(environ, start_response)

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app

    response = self.handle_exception(e)

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise

    raise value

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app

    response = self.full_dispatch_request()

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise

    raise value

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request

    rv = self.dispatch_request()

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/usr/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view

    return func(*args, **kwargs)

    File "/run/media/felipe/FFCOSTA/PROGRAMAS/antminer-monitor/antminermonitor/blueprints/asicminer/views/antminer_json.py", line 25, in pools

    return jsonify(output)

    File "/usr/lib/python3.6/site-packages/flask/json/__init__.py", line 321, in jsonify

    dumps(data, indent=indent, separators=separators) + '\n',

    File "/usr/lib/python3.6/site-packages/flask/json/__init__.py", line 179, in dumps

    rv = _json.dumps(obj, **kwargs)

    File "/usr/lib64/python3.6/json/__init__.py", line 238, in dumps

    **kw).encode(obj)

    File "/usr/lib64/python3.6/json/encoder.py", line 201, in encode

    chunks = list(chunks)

    File "/usr/lib64/python3.6/json/encoder.py", line 430, in _iterencode

    yield from _iterencode_dict(o, _current_indent_level)

    File "/usr/lib64/python3.6/json/encoder.py", line 404, in _iterencode_dict

    yield from chunks

    File "/usr/lib64/python3.6/json/encoder.py", line 325, in _iterencode_list

    yield from chunks

    File "/usr/lib64/python3.6/json/encoder.py", line 404, in _iterencode_dict

    yield from chunks

    File "/usr/lib64/python3.6/json/encoder.py", line 437, in _iterencode

    o = _default(o)

    File "/usr/lib/python3.6/site-packages/flask/json/__init__.py", line 81, in default

    return _json.JSONEncoder.default(self, o)

    File "/usr/lib64/python3.6/json/encoder.py", line 180, in default

    o.__class__.__name__)

    TypeError: Object of type 'timeout' is not JSON serializable

**Comment by red0bear** [comment]
https://file11.bitmain.com/shop-product/firmware/Antminer%20DR3/Manual/00720180927195619271eCLEJsga06CB/DR3%20Server%20Installation%20Guide.pdf
