### ISSUE TITLE
Module 'time' has no attribute 'clock' 

### ISSUE THREAD

**Issue by ark02** [anselal/antminer-monitor#173]
Looks like this method was deprecated in python 3.8 

https://stackoverflow.com/questions/58569361/attributeerror-module-time-has-no-attribute-clock-in-python-3-8

 `Traceback (most recent call last):
  File "manage.py", line 2, in <module>
    from antminermonitor.app import create_app
  File "C:\Users\op\Downloads\antminer-monitor-0.5.0\antminer-monitor-0.5.0\antminermonitor\app.py", line 3, in <module>
    from antminermonitor.blueprints.asicminer import antminer, antminer_json
  File "C:\Users\op\Downloads\antminer-monitor-0.5.0\antminer-monitor-0.5.0\antminermonitor\blueprints\asicminer\__init__.py", line 1, in <module>
    from antminermonitor.blueprints.asicminer.views.antminer import antminer
  File "C:\Users\op\Downloads\antminer-monitor-0.5.0\antminer-monitor-0.5.0\antminermonitor\blueprints\asicminer\views\antminer.py", line 10, in <module>
    from antminermonitor.blueprints.asicminer.models import Miner, MinerModel
  File "C:\Users\op\Downloads\antminer-monitor-0.5.0\antminer-monitor-0.5.0\antminermonitor\blueprints\asicminer\models\__init__.py", line 1, in <module>
    from .miner import Miner
  File "C:\Users\op\Downloads\antminer-monitor-0.5.0\antminer-monitor-0.5.0\antminermonitor\blueprints\asicminer\models\miner.py", line 1, in <module>
    from antminermonitor.extensions import db
  File "C:\Users\op\Downloads\antminer-monitor-0.5.0\antminer-monitor-0.5.0\antminermonitor\extensions.py", line 1, in <module>
    from flask_sqlalchemy import SQLAlchemy
  File "C:\Users\op\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask_sqlalchemy\__init__.py", line 39, in <module>
    _timer = time.clock
AttributeError: module 'time' has no attribute 'clock'`

**Comment by anselal** [comment]
Hi there,

yes I am aware of that. Gonna need some time to figure out how to replace it.

For now just use an older version of python

**Comment by chainworksindustries** [comment]
Same on this end for Fedora 32 x64 ...

What would be the process of configuring the package to use an earlier version when Fedora 32 has Python 3.8 installed as standard?

#crysx

**Comment by anselal** [comment]
@chainworksindustries You could use virtual environments and specify the python version.

**Comment by chainworksindustries** [comment]
Thanks ...

But I am unsure how to do this in Fedora 32. Looking online only makes things more complicated.

Is there a Step By Step instruction on how to do this? It would be very much appreciated. We need something like this, especially on a remote level, to control the ASIC and FPGA systems we currently have running, and growing at the moment. So your advice and help will be rewarded in what ever way we can.

#crysx

**Comment by anselal** [comment]
Will have to install Fedora on a VM to write some detailed instructions.
I have some alternative solutions in mind of things get too complicated

**Comment by anselal** [comment]
@chainworksindustries can we move this conversation somewhere else since it is not directly related to this issue?
Can you send me an email at t.selalmasidis@gmail.com ?

**Comment by anselal** [comment]
@chainworksindustries I've put some instructions together how to install a different python version on fedora. Just send me an email at t.selalmasidis@gmail.com and I will reply there

**Comment by brownmp** [comment]
You could replace the deprecated time.clock() with time.process_time()

**Comment by anselal** [comment]
> You could replace the deprecated time.clock() with time.process_time()

but this will only work in python 3.8 right ? or does it exist in >3.5 ???
