### ISSUE TITLE
add miner device error

### ISSUE THREAD

**Issue by vahsha** [anselal/antminer-monitor#174]
i have this error after add one miner by ip
Traceback (most recent call last):
  File "/home/vahshar/.local/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vahshar/.local/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vahshar/.local/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vahshar/.local/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vahshar/.local/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vahshar/.local/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vahshar/.local/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vahshar/.local/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vahshar/.local/lib/python2.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/vahshar/antminer-monitor-master/antminermonitor/blueprints/asicminer/views/antminer.py", line 42, in miners
    obj = getattr(sys.modules[module], cls)(miner)
  File "/home/vahshar/antminer-monitor-master/antminermonitor/blueprints/asicminer/asic_antminer.py", line 13, in __init__
    super(ASIC_ANTMINER, self).__init__(miner)
TypeError: super() argument 1 must be type, not classobj

**Comment by vahsha** [comment]
[http://s12.picofile.com/file/8404183918/Screenshot_from_2020_07_28_15_37_18.png](url)

**Comment by anselal** [comment]
thank you for using my software.

I see you are using python 2.7. Can you try python 3.5 or 3.6 and higher and let me know if you still get the same error ?

**Comment by vahsha** [comment]
vahshar@vahshar-HP-EliteBook-8440p:~/Downloads$ python -V
Python 2.7.12

**Comment by anselal** [comment]
Please try Python 3

**Comment by vahsha** [comment]
thanks dear.
in python V3.5 now working
