### ISSUE TITLE
argument 1 must be type, not classobj (S9i)

### ISSUE THREAD

**Issue by QinisoM** [anselal/antminer-monitor#177]
```
Traceback (most recent call last):
  File "{user_dir}/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/{user_dir}/Git/AntMiner/antminermonitor/blueprints/asicminer/views/antminer.py", line 42, in miners
    obj = getattr(sys.modules[module], cls)(miner)
  File "/{user_dir}/Git/AntMiner/antminermonitor/blueprints/asicminer/asic_antminer.py", line 13, in __init__
    super(ASIC_ANTMINER, self).__init__(miner)
TypeError: super() argument 1 must be type, not classobj
```

**Comment by anselal** [comment]
Use python3 instead of python2

**Comment by anselal** [comment]
@QinisoM let me know if that helped

**Comment by QinisoM** [comment]
> @QinisoM let me know if that helped

@anselal apologies for the delayed response. I'm now getting the following:
```
Traceback (most recent call last):
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/{user_dir}/Library/Python/2.7/lib/python/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/{user_dir}/Git/AntMiner/antminermonitor/blueprints/asicminer/views/antminer.py", line 42, in miners
    obj = getattr(sys.modules[module], cls)(miner)
  File "/{user_dir}/Git/AntMiner/antminermonitor/blueprints/asicminer/asic_antminer.py", line 13, in __init__
    super(ASIC_ANTMINER, self).__init__(miner)
TypeError: super() argument 1 must be type, not classobj
```

**Comment by anselal** [comment]
Sorry for that. They removed a module in version 3.9. please try again using python 3.6.
I will update the README regarding to this issue

**Comment by QinisoM** [comment]
I will try it and let you know
