### ISSUE TITLE
error when adding BW21 asic as Antminer L3+

### ISSUE THREAD

**Issue by HMCmin** [anselal/antminer-monitor#182]
KeyError
KeyError: 'STATS'

Traceback (most recent call last)
File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2463, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2449, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1866, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.7/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/home/antm/antminer-monitor-master/antminermonitor/blueprints/asicminer/views/antminer.py", line 53, in miners
for miner in results:
File "/usr/lib/python3.7/concurrent/futures/_base.py", line 586, in result_iterator
yield fs.pop().result()
File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
return self.__get_result()
File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
raise self._exception
File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/antm/antminer-monitor-master/antminermonitor/blueprints/asicminer/views/antminer.py", line 47, in poll
obj.poll()
File "/home/antm/antminer-monitor-master/antminermonitor/blueprints/asicminer/asic_antminer.py", line 38, in poll
for chain in miner_stats['STATS'][1].keys()
KeyError: 'STATS'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by anselal** [comment]
@HMCmin thanks for using my software.
Do you know if this BW21 has an API ?

**Comment by HMCmin** [comment]
sorry for late reply.
teoretical bw21 run on cgminer but I don't know witch version

**Comment by anselal** [comment]
You can try and add it as S9 or another model and there if it is running on cgminer and has the same api there 2 options you will face:

1. The model you will add the miner as will not work so you would have to delete your database and start from scratch
2. If it actually works you can navigate to localhost:5000/<miner_ip>/summary, localhost:5000/<miner_ip>/stats and post the jsons here so I can add it
