### ISSUE TITLE
unable to open database file when create_db.py

### ISSUE THREAD

**Issue by dpkeeper** [anselal/antminer-monitor#26]
version:0.2.0
platform:win10 python 2.7.13

run create_db.py:
Traceback (most recent call last):
  File "D:\projects\antminer-monitor\create_db.py", line 4, in <module>
    db.create_all()
  File "C:\ProgramData\Anaconda2\lib\site-packages\flask_sqlalchemy\__init__.py", line 946, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "C:\ProgramData\Anaconda2\lib\site-packages\flask_sqlalchemy\__init__.py", line 938, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\sql\schema.py", line 3949, in create_all
    tables=tables)
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\engine\base.py", line 1928, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "C:\ProgramData\Anaconda2\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\engine\base.py", line 1921, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\engine\base.py", line 2112, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\engine\base.py", line 2151, in _wrap_pool_connect
    e, dialect, self)
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\engine\base.py", line 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\engine\base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\pool.py", line 516, in checkout
    rec = pool._do_get()
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\pool.py", line 1229, in _do_get
    return self._create_connection()
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\engine\strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\ProgramData\Anaconda2\lib\site-packages\sqlalchemy\engine\default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

**Comment by dpkeeper** [comment]
It's because chinese character in path.
