### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by merttokgozoglu** [anselal/antminer-monitor#36]
i'm running it on ubuntu 16.04.
i tried to add more than 70 L3+ miners to the monitor list.

here's what i see most of the times:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/antminer-monitor-master/app/views/antminer.py", line 53, in miners
    worker = miner_pools['POOLS'][0]['User']
KeyError: 'POOLS'

what should i do to fix that?

**Comment by anselal** [comment]
Hi, does the app run with fewer miners installed ? I think it is due to socket timeout. I have set the timeout to 1 second. Try increading it by one until you get no errors. 
This error is reported again. Please check #33 and ket me know if this fixes the issue.

Can you give me an overview of your network setup ?

**Comment by merttokgozoglu** [comment]
hello,
thank you!
i set the timeout as 5 seconds and it's working fine.

**Comment by anselal** [comment]
Did the increase of the timeout increase the load time of the page ? How long does it take to load the info for 70 miners ?

**Comment by merttokgozoglu** [comment]
![image](https://user-images.githubusercontent.com/9316417/34312256-b5b734c4-e773-11e7-8eb2-babd0d959af1.png)
it's loading between 10-15 seconds for 84 miners.

**Comment by anselal** [comment]
Thank you for the feedback. 10-15 seconds for 84 miners is not normal though. My guess is that you have a lag in your network due to your setup. 

I have feedback from users who reported that with +30 miners the page loaded in ~0.2 seconds

**Comment by merttokgozoglu** [comment]
yes. they are in different locations. latency is 15 ms.
that must be the reason for 10-15 seconds loading time but it still is great!
thank you!

**Comment by anselal** [comment]
You are very welcome

**Comment by anselal** [comment]
I am closing this issue. Donations are always welcome !!!
