### ISSUE TITLE
debugger error

### ISSUE THREAD

**Issue by shotaatosh** [anselal/antminer-monitor#98]
I actually have no idea what this error is about, I even wiped everything and added. Also increased socket timeout but nothing helps.

`Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\antminer-monitor-master\app\views\antminer.py", line 58, in miners
    worker = miner_pools['POOLS'][0]['User']
KeyError: 'POOLS'
10.61.2.1 - - [02/May/2018 23:43:40] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
10.61.2.1 - - [02/May/2018 23:43:41] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
10.61.2.1 - - [02/May/2018 23:43:41] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
10.61.2.1 - - [02/May/2018 23:43:41] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
10.61.2.1 - - [02/May/2018 23:43:41] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -`

**Comment by anselal** [comment]
Try to increase the socket.timeout until the error is gone.

Duplicate #33
